# cargo

# [[file:~/Workspace/Programming/gosh-rs/runners/runners.note::*cargo][cargo:1]]
[package]
name = "runners"
version = "0.0.5"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
structopt = "0.2"
quicli = "0.4"
chrono = "0.4"
duct = "0.12"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.0"
futures = "0.1"
bytes = "0.4"
tokio = "0.1"
tokio-signal = "0.2"
tokio-process = "0.2"
warp = "0.1"
reqwest = "0.9"
linefeed = "0.6"
libc = "0.2"
slab = "0.4"
# nails = {path = "../nails/nails" }
# rain_task = "0.4"
# rocket = "0.4"
# mpi = { git = "https://github.com/bsteinb/rsmpi", rev = "f9aec8b8d82" }
# mpi = "0.5"

[dev-dependencies]
# cargo:1 ends here
